apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: mjrwt69/i2pdf_frontend:37cf81c3996aca597c1b5e42af61ac3b1c97b5b5
          ports:
            - containerPort: 80
