apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: mjrwt69/i2pdf_frontend:0bb76af4e7b07d209bc40f87dd5f95b160a2203a
          ports:
            - containerPort: 80
