apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: mjrwt69/i2pdf_frontend:d3e9820ad31d0432a063948812a62ebcea73813f
          ports:
            - containerPort: 80
